---
title: "Assignment #9 TidyVerse"
author: "Inna Yedzinovich"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Introduction
======================================================================================================

In this vignette, I will demonstrate how to utilize the powerful capabilities of the TidyVerse packages to analyze and visualize data. Using a dataset from FiveThirtyEight or Kaggle, I will showcase how to perform data manipulation, cleaning, and visualization using functions from the TidyVerse suite. This example will guide you through the process of loading the dataset, transforming the data to extract meaningful insights, and creating compelling visualizations to effectively communicate the results.

The following steps will be covered in the code below:

-------------------------------------------------------------------------------
Loading the Dataset: Importing the dataset into R.
Data Cleaning and Transformation: Using dplyr and tidyr to clean and reshape the data.
Data Visualization: Creating visualizations with ggplot2 to explore and present the data.


```{r }
library(tidyverse)

```

